import java.util.Date;
import java.util.List;

/**
 * The Report class handles the creation and export of reports.
 * @author Brandon Roos
 */
public class Report {
    /** A unique ID for the report. */
    private String reportID;
    /** The type of report (e.g., "PDF", "CSV"). */
    private String reportType;
    /** The date the report was generated. */
    private Date generationDate;
    /** The ID of the user who generated the report. */
    private String generatedBy;

    /**
     * Constructs a new Report object.
     *
     * @param reportID a unique ID for the report.
     * @param reportType the type of report (e.g., "PDF", "CSV").
     * @param generatedBy the ID of the user who generated the report.
     */
    public Report(String reportID, String reportType, String generatedBy) {
        this.reportID = reportID;
        this.reportType = reportType;
        this.generationDate = new Date();
        this.generatedBy = generatedBy;
    }

    /**
     * Generates a PDF report from a list of volunteer records.
     *
     * @param records a list of VolunteerRecord objects.
     */
    public void generatePDF(List<VolunteerRecord> records) {
        System.out.println("Generating PDF report for " + records.size() + " records.");
        // Implementation for PDF generation
    }

    /**
     * Exports a CSV report from a list of volunteer records.
     *
     * @param records a list of VolunteerRecord objects.
     */
    public void exportCSV(List<VolunteerRecord> records) {
        System.out.println("Exporting CSV report for " + records.size() + " records.");
        // Implementation for CSV export
    }

    /**
     * Displays the report details.
     */
    public void viewReport() {
        System.out.println("--- Report Details ---");
        System.out.println("Report ID: " + this.reportID);
        System.out.println("Report Type: " + this.reportType);
        System.out.println("Generated By: " + this.generatedBy);
        System.out.println("Generation Date: " + this.generationDate);
    }

    /**
     * Gets the unique ID of the report.
     * @return The report ID.
     */
    public String getReportID() { return reportID; }
    /**
     * Gets the type of the report.
     * @return The report type.
     */
    public String getReportType() { return reportType; }
    /**
     * Gets the date the report was generated.
     * @return The generation date.
     */
    public Date getGenerationDate() { return generationDate; }
    /**
     * Gets the ID of the user who generated the report.
     * @return The generator's ID.
     */
    public String getGeneratedBy() { return generatedBy; }
}